export type FrameworkCategory =
  | "Problem solving"
  | "Strategy"
  | "Process improvement"
  | "Supply chain";

export type Framework = {
  id: string;
  name: string;
  shortName: string;
  category: FrameworkCategory;
  description: string;
  why: string;
  when: string;
  keywords: string[];
  accent: "emerald" | "blue" | "orange" | "purple" | "teal";
  icon: string;
  steps: string[];
};

export const frameworks: Framework[] = [
  {
    id: "five-whys",
    name: "5 Whys",
    shortName: "5 Whys",
    category: "Problem solving",
    description: "Trace a visible problem back to its underlying cause.",
    why: "Repeatedly asking why helps separate the symptom from the process issue creating it.",
    when: "Use it when a specific, recurring issue needs a fast, focused root-cause investigation.",
    keywords: ["root cause", "recurring", "failure", "late", "delay", "defect", "error", "why", "complaint", "complaints", "complain", "too long", "taking too long", "keeps happening", "again"],
    accent: "emerald",
    icon: "↳",
    steps: [
      "Describe the problem as a specific, observable fact.",
      "Ask why it happened. Record the evidence behind the answer.",
      "Ask why again, using the previous answer as your starting point.",
      "Repeat until you reach a cause your team can verify and influence.",
      "Choose a countermeasure, owner, and date to check whether it worked.",
    ],
  },
  {
    id: "fishbone",
    name: "Fishbone Diagram",
    shortName: "Fishbone",
    category: "Problem solving",
    description: "Organize possible causes into clear, testable categories.",
    why: "A structured cause map helps a team look beyond the first explanation and spot patterns.",
    when: "Use it when a complex issue may have causes across people, process, tools, or inputs.",
    keywords: ["cause", "root cause", "quality", "defect", "team", "supplier", "multiple", "fishbone", "complaint", "complaints", "complain"],
    accent: "blue",
    icon: "⌁",
    steps: [
      "Write the problem at the head of your fishbone: {{problem}}",
      "Choose cause categories that fit your process (for example people, methods, tools, and materials).",
      "Brainstorm specific causes under each category without judging them yet.",
      "Use data or observation to identify which causes are most plausible.",
      "Test the leading cause and assign an action to address it.",
    ],
  },
  {
    id: "pareto",
    name: "Pareto Analysis",
    shortName: "Pareto",
    category: "Problem solving",
    description: "Find the few contributors responsible for most of the impact.",
    why: "Ranking causes by frequency or cost points limited improvement effort where it matters most.",
    when: "Use it when you have several issue types and need to decide which one to tackle first.",
    keywords: ["many", "most", "priority", "prioritize", "volume", "cost", "complaint", "complaints", "defect", "pareto", "increased"],
    accent: "orange",
    icon: "▥",
    steps: [
      "List the issue categories related to {{problem}}.",
      "Choose a measure for impact, such as frequency, cost, or time lost.",
      "Collect comparable data over a consistent period.",
      "Rank categories from highest to lowest impact and calculate their cumulative share.",
      "Focus on the largest contributors, then repeat the analysis after improvements.",
    ],
  },
  {
    id: "sipoc",
    name: "SIPOC",
    shortName: "SIPOC",
    category: "Process improvement",
    description: "Set the boundaries of a process from suppliers to customers.",
    why: "A one-page SIPOC gives everyone the same picture of process scope and handoffs.",
    when: "Use it before improving a process, especially when ownership or boundaries are unclear.",
    keywords: ["handoff", "process", "customer", "supplier", "scope", "workflow", "input", "sipoc", "order fulfillment"],
    accent: "purple",
    icon: "▤",
    steps: [
      "Name the process connected to {{problem}} and define its start and end.",
      "List the major process steps at a high level.",
      "Identify the outputs created by those steps.",
      "Name the customers who receive each output and what they need.",
      "Work backward to list required inputs and the suppliers who provide them.",
    ],
  },
  {
    id: "process-mapping",
    name: "Process Mapping",
    shortName: "Process map",
    category: "Process improvement",
    description: "Make the actual work, decisions, and handoffs visible.",
    why: "Mapping work as it happens reveals rework, waits, and unclear ownership that are easy to miss.",
    when: "Use it when a workflow feels slow or confusing and the team needs a shared current-state view.",
    keywords: ["workflow", "process", "steps", "handoff", "waiting", "approval", "manual", "map", "order fulfillment", "fulfillment", "too long", "taking too long", "delivery time", "lead time", "slow"],
    accent: "blue",
    icon: "⌘",
    steps: [
      "Choose one process tied to {{problem}} and identify its start and finish.",
      "Talk to the people doing the work and map the real steps in order.",
      "Add decisions, rework loops, queues, and handoffs between teams.",
      "Walk the map with process participants and mark delays or failure points.",
      "Design and test a future-state map with clear owners and measures.",
    ],
  },
  {
    id: "swot",
    name: "SWOT",
    shortName: "SWOT",
    category: "Strategy",
    description: "Balance internal strengths and weaknesses with external forces.",
    why: "SWOT turns a broad business question into a balanced view of what helps and what threatens success.",
    when: "Use it when evaluating a new initiative, team direction, or business challenge.",
    keywords: ["strategy", "growth", "opportunity", "threat", "strength", "market", "launch", "swot"],
    accent: "purple",
    icon: "✳",
    steps: [
      "Frame the strategic question around {{problem}}.",
      "List internal strengths that could help address it.",
      "List internal weaknesses or capability gaps to account for.",
      "Identify external opportunities and threats using current evidence.",
      "Turn the most important connections into prioritized actions.",
    ],
  },
  {
    id: "pestel",
    name: "PESTEL",
    shortName: "PESTEL",
    category: "Strategy",
    description: "Scan political, economic, social, technological, environmental, and legal forces.",
    why: "PESTEL helps spot external changes that could reshape a plan before they become surprises.",
    when: "Use it for market entry, long-term planning, or decisions exposed to regulatory or economic change.",
    keywords: ["regulation", "market", "external", "economic", "technology", "policy", "environment", "pestel"],
    accent: "teal",
    icon: "◎",
    steps: [
      "Clarify the decision or challenge: {{problem}}.",
      "Scan political and economic changes that could affect the decision.",
      "Consider social and technological shifts relevant to customers and operations.",
      "Review environmental and legal requirements or emerging expectations.",
      "Rank forces by likelihood and impact, then decide how to respond.",
    ],
  },
  {
    id: "porters-five-forces",
    name: "Porter’s Five Forces",
    shortName: "Five Forces",
    category: "Strategy",
    description: "Understand the competitive forces shaping an industry.",
    why: "The five forces explain where competitive pressure comes from and how it affects profitability.",
    when: "Use it when entering a market, reviewing positioning, or assessing competitive pressure.",
    keywords: ["competition", "competitor", "industry", "pricing", "market share", "supplier power", "entry", "porter"],
    accent: "orange",
    icon: "⬡",
    steps: [
      "Define the industry and strategic question behind {{problem}}.",
      "Assess rivalry among existing competitors and the threat of new entrants.",
      "Evaluate substitute products or services customers could choose.",
      "Consider buyer and supplier bargaining power.",
      "Identify the strongest forces and implications for your position.",
    ],
  },
  {
    id: "value-chain",
    name: "Value Chain Analysis",
    shortName: "Value chain",
    category: "Strategy",
    description: "See where activities create value and where cost or friction builds up.",
    why: "Reviewing activities end to end highlights where capabilities can create an advantage.",
    when: "Use it when improving margins, differentiating an offer, or deciding what to build in-house.",
    keywords: ["value", "cost", "margin", "customer", "activity", "advantage", "sourcing", "value chain"],
    accent: "emerald",
    icon: "⌁",
    steps: [
      "Set the business boundary and frame {{problem}} in terms of value.",
      "Map primary activities from inbound inputs through delivery and service.",
      "Add supporting activities such as technology, people, and procurement.",
      "Estimate the cost and customer value of each activity.",
      "Choose activities to strengthen, simplify, partner, or redesign.",
    ],
  },
  {
    id: "bcg-matrix",
    name: "BCG Matrix",
    shortName: "BCG Matrix",
    category: "Strategy",
    description: "Compare a portfolio by market growth and relative market share.",
    why: "The portfolio view supports clearer investment and resource-allocation decisions.",
    when: "Use it when balancing investment across products, services, or business units.",
    keywords: ["portfolio", "product", "investment", "market growth", "business unit", "resource", "bcg"],
    accent: "purple",
    icon: "▦",
    steps: [
      "Choose the product or business portfolio affected by {{problem}}.",
      "Estimate market growth for each item using a consistent source.",
      "Compare relative market share against the leading competitor.",
      "Place each item in the matrix and challenge the assumptions behind its position.",
      "Set a deliberate investment, maintenance, or exit decision for each item.",
    ],
  },
  {
    id: "root-cause",
    name: "Root Cause Analysis",
    shortName: "Root cause",
    category: "Problem solving",
    description: "Investigate the evidence behind a persistent operational issue.",
    why: "A disciplined investigation avoids treating symptoms and reduces the chance of recurrence.",
    when: "Use it when an issue has meaningful impact, repeats, or needs a documented corrective action.",
    keywords: ["root cause", "recurring", "failure", "incident", "defect", "error", "investigate", "problem", "complaint", "complaints", "complain", "increased"],
    accent: "emerald",
    icon: "⌕",
    steps: [
      "State the issue, its impact, and the evidence that it occurred.",
      "Contain immediate effects while protecting relevant evidence.",
      "Build a timeline and gather facts from the people and systems involved.",
      "Test potential contributing causes against evidence, not assumptions.",
      "Implement corrective actions and monitor recurrence of {{problem}}.",
    ],
  },
  {
    id: "bottleneck-analysis",
    name: "Bottleneck Analysis",
    shortName: "Bottleneck",
    category: "Process improvement",
    description: "Find the step that limits the throughput of an entire process.",
    why: "Improving the constraint can raise total flow more effectively than optimizing every step.",
    when: "Use it when work queues up, output is capped, or delivery times keep slipping.",
    keywords: ["capacity", "queue", "throughput", "slow", "delay", "waiting", "backlog", "bottleneck", "order fulfillment", "fulfillment", "too long", "taking too long", "delivery time", "lead time"],
    accent: "orange",
    icon: "⫶",
    steps: [
      "Define the flow and the output affected by {{problem}}.",
      "Measure demand, throughput, and waiting time at each step.",
      "Find the step with the highest sustained utilization or queue.",
      "Protect and make the constraint productive before adding capacity.",
      "Re-measure flow and look for the next constraint.",
    ],
  },
  {
    id: "capacity-analysis",
    name: "Capacity Analysis",
    shortName: "Capacity",
    category: "Process improvement",
    description: "Compare available capability with the work that needs to be done.",
    why: "Capacity estimates show whether demand, staffing, equipment, or variability is driving a gap.",
    when: "Use it when planning staffing, shifts, service levels, or production output.",
    keywords: ["capacity", "staffing", "resource", "demand", "utilization", "workload", "overtime"],
    accent: "blue",
    icon: "▥",
    steps: [
      "Set the planning horizon and define the output needed to resolve {{problem}}.",
      "Estimate demand by time period, including known peaks and variation.",
      "Calculate effective capacity after availability, skills, and planned downtime.",
      "Compare demand with capacity and locate the timing and type of any gap.",
      "Evaluate options such as scheduling, cross-training, process changes, or added capacity.",
    ],
  },
  {
    id: "dmaic",
    name: "DMAIC",
    shortName: "DMAIC",
    category: "Process improvement",
    description: "Improve an existing process with a measured, five-phase approach.",
    why: "DMAIC connects a defined problem to measurable root causes, tested improvements, and control.",
    when: "Use it for a significant process problem where performance data is available or can be collected.",
    keywords: ["quality", "variation", "defect", "measure", "improve", "control", "process", "dmaic", "complaint", "complaints", "increased"],
    accent: "teal",
    icon: "◌",
    steps: [
      "Define {{problem}}, the customer impact, project boundary, and goal.",
      "Measure current performance with a trustworthy baseline.",
      "Analyze data to validate the causes of poor performance.",
      "Improve the process by testing solutions against the causes.",
      "Control the gains with process owners, measures, and a response plan.",
    ],
  },
  {
    id: "pdca",
    name: "PDCA",
    shortName: "PDCA",
    category: "Process improvement",
    description: "Run a small improvement experiment and learn from the result.",
    why: "Short learning cycles reduce risk and make it easier to adapt an improvement before scaling.",
    when: "Use it when a team wants to test a change quickly with clear measures.",
    keywords: ["experiment", "test", "continuous improvement", "pilot", "change", "plan", "pdca"],
    accent: "teal",
    icon: "↻",
    steps: [
      "Plan a small change aimed at {{problem}} and define what success looks like.",
      "Do: run the test on a limited scale and record what happened.",
      "Check: compare results with the prediction and look for side effects.",
      "Act: adopt, adapt, or abandon the change based on what you learned.",
      "Repeat the cycle with a refined change or a new improvement opportunity.",
    ],
  },
  {
    id: "scor",
    name: "SCOR Model",
    shortName: "SCOR",
    category: "Supply chain",
    description: "Assess supply-chain performance across plan, source, make, deliver, and return.",
    why: "A common end-to-end process language makes supply-chain gaps easier to locate and compare.",
    when: "Use it when a supply chain has service, cost, reliability, or resilience challenges.",
    keywords: ["supply chain", "supplier", "delivery", "logistics", "fulfillment", "warehouse", "scor", "order fulfillment", "running out", "run out", "best-selling", "out of stock"],
    accent: "blue",
    icon: "⌘",
    steps: [
      "Frame the supply-chain outcome affected by {{problem}}.",
      "Map the relevant plan, source, make, deliver, and return processes.",
      "Measure reliability, responsiveness, agility, cost, and asset performance.",
      "Trace gaps across process handoffs and identify their likely causes.",
      "Prioritize improvements with owners, targets, and review cadence.",
    ],
  },
  {
    id: "inventory-abc",
    name: "Inventory ABC Analysis",
    shortName: "ABC inventory",
    category: "Supply chain",
    description: "Segment inventory so control effort matches business value.",
    why: "ABC grouping focuses attention on the items that drive the largest share of inventory value.",
    when: "Use it when inventory is hard to control or replenishment effort needs prioritization.",
    keywords: ["inventory", "stock", "sku", "replenishment", "warehouse", "obsolete", "abc", "running out", "run out", "best-selling", "out of stock", "stockout", "stock-out", "shortage"],
    accent: "orange",
    icon: "▤",
    steps: [
      "Choose an inventory population and define the issue: {{problem}}.",
      "Calculate annual usage value for each item using the same period and method.",
      "Rank items by value and calculate the cumulative share.",
      "Set practical A, B, and C groups, then validate them with operational context.",
      "Apply tighter review to high-value items and simplify controls for low-value items.",
    ],
  },
  {
    id: "eoq",
    name: "EOQ",
    shortName: "EOQ",
    category: "Supply chain",
    description: "Estimate an order quantity that balances ordering and holding costs.",
    why: "EOQ provides a useful starting point for reducing the combined cost of replenishment and inventory.",
    when: "Use it when demand is reasonably stable and you need a baseline replenishment quantity.",
    keywords: ["inventory", "order quantity", "reorder", "holding cost", "ordering cost", "stock", "eoq", "running out", "run out", "best-selling", "out of stock", "stockout", "stock-out", "shortage"],
    accent: "teal",
    icon: "∿",
    steps: [
      "Select an item related to {{problem}} and confirm demand is reasonably predictable.",
      "Estimate annual demand, cost per order, and annual holding cost per unit.",
      "Calculate EOQ using the square root of (2 × annual demand × order cost ÷ annual holding cost).",
      "Compare the result with supplier minimums, lead times, and storage constraints.",
      "Pilot the quantity and review service, inventory, and total replenishment cost.",
    ],
  },
  {
    id: "toc",
    name: "Theory of Constraints",
    shortName: "Theory of Constraints",
    category: "Process improvement",
    description: "Improve system output by managing the most limiting constraint.",
    why: "TOC focuses improvement on the single constraint currently limiting the whole system.",
    when: "Use it when local improvements are not increasing total throughput or delivery performance.",
    keywords: ["constraint", "throughput", "capacity", "bottleneck", "queue", "flow", "toc"],
    accent: "purple",
    icon: "⫶",
    steps: [
      "Identify the system goal and how {{problem}} is limiting it.",
      "Find the current constraint using queues, throughput, and direct observation.",
      "Exploit the constraint: make the best use of the capacity already available.",
      "Subordinate other work to the constraint and elevate it only if needed.",
      "Repeat the process when the constraint moves, avoiding inertia.",
    ],
  },
];

export const categories: Array<"All frameworks" | FrameworkCategory> = [
  "All frameworks",
  "Problem solving",
  "Process improvement",
  "Strategy",
  "Supply chain",
];

export function getFramework(id: string) {
  return frameworks.find((framework) => framework.id === id);
}
